name = "GeometricIntegratorsDiffEq"
uuid = "5a33fad7-5ce4-5983-9f5d-5f26ceab5c96"
version = "2.0.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLLogging = "a6db7da4-7206-11f0-1eab-35f2a5dbe1d1"
SimpleSolvers = "36b790f5-6434-4fbe-b711-1f64a1e2f6a2"

[compat]
DiffEqBase = "6.62, 7"
GeometricIntegrators = "0.15.5, 0.16"
ODEProblemLibrary = "0.1.8, 1"
RecursiveArrayTools = "3, 4"
SafeTestsets = "0.0.1, 0.1"
SciMLBase = "2, 3"
SciMLLogging = "1.10.1, 2"
SciMLTesting = "2.4"
SimpleSolvers = "0.7, 0.9"
Test = "1.10"
julia = "1.10"

[extras]
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLTesting = "09d9d899-5365-40a9-917a-5f67fddea283"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ODEProblemLibrary", "SafeTestsets", "SciMLTesting", "Test"]
